version: "3"
services:
  app:
    build: app
    container_name: app
    env_file: my_vars.env

  nginx:
    build: html
    container_name: web
    env_file: my_vars.env
    ports:
      - 9000
    expose:
      - 9000
    depends_on:
      - app
