version: "3"
services:
  app:
    image: clintonwong/app-backend:latest
    container_name: app
    env_file: my_vars.env

  nginx:
    image: clintonwong/web-frontend:latest
    container_name: web
    env_file: my_vars.env
    ports:
      - 8080:80
    expose:
      - 8080
    depends_on:
      - app
